/*
 * AppConstants
 * These are the variables that determine what our central data store (reducer.js)
 * changes in our state. When you add a new action, you have to add a new constant here
 *
 * Follow this format:
 * export const YOUR_ACTION_CONSTANT = 'YOUR_ACTION_CONSTANT';
 */

/* App Constants */
export const SENDING_REQUEST = 'SENDING_REQUEST'
export const SET_AUTH = 'SET_AUTH'
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE'
export const CLEAR_ERROR_MESSAGES = 'CLEAR_ERROR_MESSAGES'

/* Member Constants */
export const MEMBER_INFO_HAS_ERRORED = 'MEMBER_INFO_HAS_ERRORED'
export const MEMBER_INFO_FETCH_DATA_SUCCESS = 'MEMBER_INFO_FETCH_DATA_SUCCESS'
export const MEMBER_INFO_IS_LOADING = 'MEMBER_INFO_IS_LOADING'
export const LOAD_COMPLETE_SIGNUP_LOADING = 'LOAD_COMPLETE_SIGNUP_LOADING'
export const LOAD_COMPLETE_SIGNUP_SUCCESS = 'LOAD_COMPLETE_SIGNUP_SUCCESS'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const LOAD_SIGNUP_SUCCESS = 'LOAD_SIGNUP_SUCCESS'
export const CREATE_USER_LOADING = 'CREATE_USER_LOADING'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const BRIEF_INFO_FETCH_DATA_SUCCESS = 'BRIEF_INFO_FETCH_DATA_SUCCESS'
export const BRIEF_RESPONSES_FETCH_DATA_SUCCESS = 'BRIEF_RESPONSES_FETCH_DATA_SUCCESS'
export const BRIEF_INFO_HAS_ERRORED = 'BRIEF_INFO_HAS_ERRORED'
export const BRIEF_RESPONSE_SUCCESS = 'BRIEF_RESPONSE_SUCCESS'
export const BRIEF_RESPONSE_FAILURE = 'BRIEF_RESPONSE_FAILURE'
export const BRIEF_RESPONSE_DUPLICATE_FAILURE = 'BRIEF_RESPONSE_DUPLICATE_FAILURE'
export const GET_RESET_DATA_SUCCESS = 'GET_RESET_DATA_SUCCESS'
export const GET_RESET_DATA_FAILURE = 'GET_RESET_DATA_FAILURE'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE'
export const RESET_PASSWORD_EMAIL_FAILURE = 'RESET_PASSWORD_EMAIL_FAILURE'
export const RESET_PASSWORD_EMAIL_SUCCESS = 'RESET_PASSWORD_EMAIL_SUCCESS'
export const FEEDBACK_SUCCESS = 'FEEDBACK_SUCCESS'
export const SET_AUTH_FRAMEWORK_ERROR = 'SET_AUTH_FRAMEWORK_ERROR'
export const SELLER_DASHBOARD_SUCCESS = 'SELLER_DASHBOARD_SUCCESS'
export const SPECIALIST_NAME = 'SPECIALIST_NAME'
export const SPECIALIST_NUMBER = 'SPECIALIST_NUMBER'
export const ADD_ANOTHER_SPECIALIST = 'ADD_ANOTHER_SPECIALIST'
