/*
 * AppConstants
 * These are the variables that determine what our central data store (reducer.js)
 * changes in our state. When you add a new action, you have to add a new constant here
 *
 * Follow this format:
 * export const YOUR_ACTION_CONSTANT = 'YOUR_ACTION_CONSTANT';
 */

/* App Constants */
export const SENDING_REQUEST = 'SENDING_REQUEST'
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE'
export const CLEAR_ERROR_MESSAGES = 'CLEAR_ERROR_MESSAGES'
export const SET_AUTH = 'SET_AUTH'
export const GET_RESET_DATA_SUCCESS = 'GET_RESET_DATA_SUCCESS'
export const GET_RESET_DATA_FAILURE = 'GET_RESET_DATA_FAILURE'
export const RESET_PASSWORD_EMAIL_SUCCESS = 'RESET_PASSWORD_EMAIL_SUCCESS'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const PROFILE_UPDATED = 'PROFILE_UPDATED'
export const SET_REGIONS = 'SET_REGIONS'
export const SET_SERVICES = 'SET_SERVICES'
export const SET_REGION = 'SET_REGION'
export const SET_CATEGORY = 'SET_CATEGORY'
export const SET_TABLE_DATA = 'SET_TABLE_DATA'
export const SET_REGION_ACCORDION_OPEN = 'SET_REGION_ACCORDION_OPEN'
export const SET_CATEGORY_ACCORDION_OPEN = 'SET_CATEGORY_ACCORDION_OPEN'
export const SET_TABLE_FOCUS = 'SET_TABLE_FOCUS'
export const SET_EDIT_SERVICE_DATA = 'SET_EDIT_SERVICE_DATA'
export const SET_PRICES_DATA = 'SET_PRICES_DATA'
export const SET_STEP = 'SET_STEP'
export const SET_PRICE_TO_EDIT_DATA = 'SET_PRICE_TO_EDIT_DATA'
export const SET_SERVICE_TO_EDIT_IN_STATE = 'SET_SERVICE_TO_EDIT_IN_STATE'
export const SET_PRICE_TO_EDIT_ID = 'SET_PRICE_TO_EDIT_ID'
export const SET_ONE_PRICE = 'SET_ONE_PRICE'
export const SET_BUTTON_CLICK = 'SET_BUTTON_CLICK'
export const SET_SUPPLIER = 'SET_SUPPLIER'
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE'
export const RESTART_EDIT_PRICING = 'RESTART_EDIT_PRICING'
export const SET_SUPPLIER_DATA = 'SET_SUPPLIER_DATA'
export const SET_PROFILE_DATA = 'SET_PROFILE_DATA'
export const HIDE_NAV = 'HIDE_NAV'
export const BUYER_SUPPLIERS = 'BUYER_SUPPLIERS'
export const SET_SERVICE_DATA = 'SET_SERVICE_DATA'
export const SET_SUPPLIER_CODE = 'SET_SUPPLIER_CODE'
export const SET_PRICE_HISTORY_DATA = 'SET_PRICE_HISTORY_DATA'
export const DISPLAY_STEP_2 = 'DISPLAY_STEP_2'
export const SET_INVITATION_DATA = 'SET_INVITATION_DATA'
export const SET_USER_TO_CREATE_DATA = 'SET_USER_TO_CREATE_DATA'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
